### PR TITLE
meson: Do not require gstreamer-check-1.0 when tests are disabled

### PR DESCRIPTION
**Pull request by xclaesse**

### CODE REVIEW

**Comment by xclaesse** [comment]
@jsalas98 Sorry if you're not the one to ask, but since you did the last merges, can you have a look at this please?

**Review by michaelgruner — APPROVED** [review]
Looks good to me. Can you rebase to the latest develop so I can merge in?

**Comment by xclaesse** [comment]
@michaelgruner rebased now.

**Comment by xclaesse** [comment]
@michaelgruner can we get this merged please?

**Comment by xclaesse** [comment]
Thanks! OOC, when is next release planned?

**Pull request merged**
